name: Add Issues and PRs to the Community Board

on:
  issues:
    types:
      - opened
      - reopened
      - transferred
      - labeled

  pull_request:
    types:
      - labeled
      - opened
      - reopened

jobs:

  show-info:
    name: Show event info
    runs-on: ubuntu-latest
    steps:
      - name: Show event info
        run: |
          echo "event_name: ${{ github.event_name }}"
          echo "issue number: ${{ github.event.issue.number }}"
          echo "issue author: ${{ github.event.issue.user.login }}"
          echo "PR author: ${{ github.event.pull_request.user.login }}"

  add-issue-to-board:
    name: Add issue to the community board
    if: github.event_name == 'issues' && !contains(fromJson('["wagoodman"]'), github.event.issue.user.login)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/users/wagoodman/projects/1
          github-token: ${{ secrets.OSS_PROJECT_GH_TOKEN }}
          labeled: bug, enhancement
          label-operator: OR

  add-pr-to-board:
    name: Add PR to the community board
    if: github.event_name == 'pull_request' && !contains(fromJson('["wagoodman"]'), github.event.pull_request.user.login)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/users/wagoodman/projects/1
          github-token: ${{ secrets.OSS_PROJECT_GH_TOKEN }}
          labeled: bug, enhancement
          label-operator: OR
